### ISSUE TITLE
PuppetDB 2.3 kann nur API v3

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-puppetdb#1]
PuppetDB 2.3.8, wie in Ubuntu Precise enthalten, kann nur API v3. Die Implementierung von v4 ist experimental und anders, als PuppetDB 3+ das macht. Das Modul funktioniert somit also nur mit der Auswahl v3.

Daher vielleicht bei der Auswahl der API Version die 2.3 mit bei V3 auflisten, nicht bei v4.

**Comment by Thomas-Gelf** [comment]
Danke für den Tipp, hab das issue leider komplett übersehen bzw bekam keine Notification dafür. Hast du ggf noch mehr Infos dazu, sprich woran scheitert es? Das Modul ist ziemlich quick & dirty, macht aber brav seinen Job. Es nutzt nur einen kleinen Teil der PuppetDB API, vielleicht kann ich ja um das was nicht geht "anders drumherumarbeiten". Die v4 hat nämlich ein paar nette Features die das Ganze bequemer und schneller machen. Dazu gehört z.B. das Dropdown mit den verfügbaren Resource-Typen.

Besten Dank
Tom

**Comment by Thomas-Gelf** [comment]
Bitte einfach neu öffnen falls hierzu noch was ansteht, ich schließe es mal.
