### ISSUE TITLE
Add  template to host, based on a facts in the PuppetDB

### ISSUE THREAD

**Issue by linuxmail** [Icinga/icingaweb2-module-puppetdb#13]
hi,

I try to add a template to hosts, via based on a fact. It works, if I use "certname=host.foo", but I need something like:

Import template "nginx-template", if facts.puppet_modules=*nginx*, like I have it on the screenshot.

![bildschirmfoto vom 2017-11-30 11-00-30](https://user-images.githubusercontent.com/1276233/33425017-cf25d34c-d5bd-11e7-827e-9368be79e0d3.png)

Is that possible?

cu denny

**Comment by Thomas-Gelf** [comment]
It should work, but not with the wildcard. Filtering for `facts.puppet_classes=nginx|facts.puppet_classes=nginx_whatever` should be fine.

**Comment by Thomas-Gelf** [comment]
@linuxmail: and eventually have a look at the proposed solution in this [Director issue](https://github.com/Icinga/icingaweb2-module-director/issues/1506), it could fit your scenario.
