### ISSUE TITLE
import source list wrong when setup done by puppet-icingaweb2 module

### ISSUE THREAD

**Issue by spali** [Icinga/icingaweb2-module-puppetdb#14]
Please check issue https://github.com/Icinga/puppet-icingaweb2/issues/197.
I'm not sure who should fix that, or if I did anything wrong in my setup.
If it has to be fixed in `Icinga/puppet-icingaweb2`, then this is just for documentation about the problem when used with `Icinga/puppet-icingaweb2`.

**Comment by Thomas-Gelf** [comment]
This should have been fixed in the linked issue. In case you're still facing related problems please let me know.
