### ISSUE TITLE
Clone / import / export sync rules

### ISSUE THREAD

**Issue by linuxmail** [Icinga/icingaweb2-module-puppetdb#15]
hi,

I have three PuppetDBs all with many sync rules and I have to add a new PuppetDB. It would be great, if I can clone / export / import the sync rules.

**Comment by Thomas-Gelf** [comment]
Hi @linuxmail,

please follow Director [issue #1409](https://github.com/Icinga/icingaweb2-module-director/issues/1409), it will implement what you're asking for!

Cheers,
Thomas

**Comment by linuxmail** [comment]
hi,

very cool. Big thanks!
