### ISSUE TITLE
Exported resources from Puppet using icinga2 puppet module

### ISSUE THREAD

**Issue by mixacha** [Icinga/icingaweb2-module-puppetdb#4]
Hi,
how to configure sync settings regarding exported variables ? We're using Puppet to generate icinga2 configs, export them to PuppetDB and then collect on icinga master.
We'd like to switch to use this module due to outlined benefits (performance mainly), however when adding new hosts how do we map parameters from PuppetDB into icinga fields, as these already contain all variables?

**Comment by Thomas-Gelf** [comment]
Sorry for coming back that late on you. Your questions where pretty basic, have you been able to figure out how it works in the meantime?
