### ISSUE TITLE
Parse error exception when using a "Resources" query type.

### ISSUE THREAD

**Issue by erezzarum** [Icinga/icingaweb2-module-puppetdb#7]
Parse error: syntax error, unexpected '(', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) 
Seems to be related to [FilterRenderer.php](https://github.com/Icinga/icingaweb2-module-puppetdb/blob/6ed028d948e08dc65c8eb0429eb19c2e4f441fe0/library/Puppetdb/FilterRenderer.php), the change from `return new FilterRenderer($filter);` to  `return static($filter);` at `public static function forFilter(Filter $filter)`

So far i didn't witness any side effects.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
