### ISSUE TITLE
Facts does not work with preview/output with PuppetDB 4

### ISSUE THREAD

**Issue by druchoo** [Icinga/icingaweb2-module-puppetdb#9]
PuppetDB: `4.2.2`
icingaweb2-module-puppetdb: `14afc2a`
Query Type `Nodes`
Resource Type `Host`

Same as #2. Created new issue since that one was closed.

> When adding the PuppetDB output, everything seems OK, except that preview does not present any facts in any other colums than the "massive" facts one.

Here's a screenshot. The column names are a bit mangled because wasn't easy to take a scrolling screenshot but you can see the empty columns.

![icinga](https://cloud.githubusercontent.com/assets/2237523/25315912/33fd362a-282b-11e7-9c1f-617e65610ea8.png)

> Trying to apply modifiers to the single facts does not yield any different results either.
> The module correctly guesses classes, nodes, resources and the name of the facts but it does not return the data from them.

Individual fact columns are empty so they're not able to be imported as-is or modified in any way. Hope this clarifies the issue. Let me know if you need more info and i'll try to provide.

**Comment by Thomas-Gelf** [comment]
@druchoo: this should have been addressed for Director v1.4.0 - could you please check whether it now works as expected?

**Comment by druchoo** [comment]
@Thomas-Gelf, I'm a few commits behind master on `d41fbbf63499eba86fe85f835cde5fa8d34a1f39` and this looks ok. I no longer see the facts.* column in the preview but I'm able to work with them in sync rules. Unfortunately my preview still scrolls very far to the right because my `facts` dict contains some very long strings but I can live with that.

**Comment by Thomas-Gelf** [comment]
@druchoo: in case you want this to look better please open a dedicate issue in the Director project, combined with a screen-shot showing the problem. Sooner or later we might tackle this ;-)

**Comment by druchoo** [comment]
Nah it's good. I don't want time wasted on that. Thanks though!
